/** Draft copy for Northstar's real authentication screens; the UI is not part of this Console preview. */
export const liveAuthTranslations = {
  en: {
    emailLabel: "Email address",
    displayNameLabel: "Display name",
    invalidEmail: "Enter a valid email address.",
    requiredName: "Enter your name.",
    correctFields: "Review the highlighted fields and try again.",
    loginTitle: "Sign in",
    loginIntro: "Enter your email, then continue with a passkey. You can also use a passkey without entering email if your device offers it.",
    signupTitle: "Create your account",
    signupIntro: "Start with your email. We will send a short verification code before you create a passkey.",
    signUp: "Continue",
    emailContinue: "Continue",
    verifyEmailTitle: "Check your email",
    verifyEmailIntro: "Enter the 12-character code sent to this address. The code expires in 10 minutes.",
    verificationCodeLabel: "Email verification code",
    verificationCodeHint: "This is not a recovery code. Never share a recovery code in chat.",
    verifyEmail: "Verify email",
    resendVerification: "Send a new code",
    verificationResent: "If this address can be registered, a new code has been sent.",
    developmentInboxLabel: "Development only: show the local email code",
    developmentInboxHelp: "This local inbox is only for development. Production registration requires a configured email sender.",
    developmentInboxLoaded: "Local verification code loaded. Keep it private.",
    invalidVerificationCode: "Enter the 12-character email verification code.",
    emailVerified: "Email verified. Continue by creating a passkey.",
    createPasskeyTitle: "Create your passkey",
    createPasskeyDescription: "Use your phone or computer's fingerprint, face unlock, or PIN to sign in securely. You won't need a password.",
    createPasskeyAction: "Create passkey",
    saveRecoveryCodesTitle: "Save your recovery codes",
    saveRecoveryCodesDescription: "These six codes help you recover your account if you lose access to your passkeys. Each code can be used once. Save them in a trusted password manager or an encrypted, physically protected offline copy.",
    recoveryCodesCopy: "Copy codes",
    recoveryCodesCopied: "Recovery codes copied. Store them somewhere secure.",
    recoveryCodesDownload: "Download codes as a text file",
    recoveryCodesDownloadWarning: "The downloaded file contains account recovery secrets. Keep it protected and delete extra copies.",
    recoveryCodesPrint: "Print codes",
    recoveryCodesAcknowledgement: "I saved these codes somewhere secure. I understand they are shown only once.",
    recoveryCodesContinue: "Finish setup",
    clipboardUnavailable: "Copy is unavailable here. Select the codes and copy them manually.",
    setupComplete: "Complete",
    accountReadyTitle: "Your account is ready",
    accountReadyDescription: "Your email is verified, your passkey is registered, and your six recovery codes were issued.",
    verifiedEmailLabel: "Verified email",
    registeredPasskeyLabel: "Passkey registered",
    recoveryCodesIssuedLabel: "Recovery codes saved",
    continueToAccount: "Go to your account",
    discoverableSignIn: "Use a passkey without email",
    deviceLinkTitle: "Sign in on a new device",
    deviceLinkIntro: "If you are signed in on another device, you can approve this request there. You will not need to scan a QR code.",
    deviceLinkStart: "Approve using my existing device",
    deviceLinkComparisonLabel: "Request comparison code",
    deviceLinkComparisonHint: "Make sure this code matches the one shown on your existing device before approving.",
    deviceLinkPending: "Waiting for approval from your existing device…",
    deviceLinkApproved: "Your request was approved. Create a passkey on this device to finish.",
    deviceLinkRejected: "The request was rejected. No passkey was added.",
    deviceLinkExpired: "This request expired. Start again or choose another sign-in method.",
    deviceLinkCreatePasskey: "Create passkey on this device",
    deviceLinkCancel: "Cancel request",
    deviceLinkStartOver: "Try another request",
    deviceApprovalTitle: "New device requests",
    deviceApprovalDescription: "Approve only when you started the request and the comparison code matches the new device.",
    deviceApprovalEmpty: "No pending device requests.",
    deviceApprovalPrompt: "Are you adding a new device? Verify with your passkey to approve this request.",
    deviceApprovalCodeLabel: "Enter the code shown on the new device",
    deviceApprovalCodeHint: "Compare all six characters before you approve.",
    deviceApprovalConfirmation: "I checked that this code matches the code on the new device.",
    deviceApprovalApprove: "Verify and approve",
    deviceApprovalReject: "Reject request",
    deviceApprovalComplete: "The new device is approved.",
    deviceApprovalRefresh: "Refresh requests",
    signIn: "Sign in",
    passkeyLogin: "Sign in with a passkey",
    passkeyEnroll: "Add a passkey",
    passkeyEnrollmentTitle: "Add a passkey",
    passkeyEnrollmentDescription: "Add a passkey to sign in securely on this device. Follow the browser prompt.",
    passkeyPrompt: "Follow the passkey prompt on your device to continue.",
    passkeyLoading: "Waiting for passkey verification…",
    passkeyCancel: "Cancel passkey sign-in",
    recoveryCodeLabel: "Recovery code",
    recoveryCodeHint: "Enter one of your saved recovery codes. Recovery codes are separate from email verification codes.",
    recoveryLink: "Use a recovery code",
    recoveryTitle: "Recover your account",
    recoveryIntro: "Use your email and one unused recovery code to register a replacement passkey. Recovery will not sign you in before the new passkey is verified.",
    beginRecovery: "Begin recovery",
    completeRecovery: "Verify recovery code",
    recoveryRegisterPasskey: "Register replacement passkey",
    recoveryReplacementIntro: "Your recovery code was accepted. Register a new passkey to complete recovery. Your old sessions and passkeys will be revoked.",
    recoveryCodesSave: "Save these new recovery codes offline. They are shown only once. Anyone with an unused code can recover this account.",
    recoveryPasskeyError: "The replacement passkey could not be registered. Try again, or cancel and begin a new recovery with another unused code.",
    recoveryCancelled: "Recovery was cancelled. No passkey was replaced.",
    backToSignIn: "Back to sign in",
    recoveryRequestAccepted: "If the details match an account that can be recovered, next steps will be shown here.",
    genericFailure: "We couldn't complete that request. Check your details and try again.",
    rateLimited: "Too many attempts. Wait a moment, then try again.",
    networkError: "We couldn't reach the service. Check your connection and try again.",
    sessionExpired: "Your session expired. Sign in again to continue.",
    passkeyFailure: "Passkey verification didn't complete. Try again or choose another sign-in method.",
    stepUpTitle: "Verify this action",
    stepUpIntro: "Use your passkey to continue. If you cancel, no change is made.",
    stepUpButton: "Continue with passkey",
    stepUpWorking: "Waiting for passkey verification…",
    stepUpCancel: "Cancel verification",
    exportTitle: "Export account data",
    exportDescription: "Request an export of your account data. This action may require passkey verification and is subject to your access policy.",
    policyDenied: "This action is not available under your current access policy.",
    exportSuccess: "Your export request was accepted. Check this page for status.",
    deleteTitle: "Delete account",
    deleteDescription: "This permanently deletes this account and its profile data, signs out all sessions, and removes saved authenticators and recovery codes. Sentriq will require a fresh security check before deletion.",
    deletePrompt: "Review what will be removed before continuing.",
    deleteConfirmLabel: "Continue to security check",
    exportFormat: "Download format",
    jsonFormatHint: "A structured JSON file.",
    csvFormatHint: "A table you can open in spreadsheet software.",
    requestExport: "Request protected export",
    policyTitle: "Protected action policy",
    haveAccount: "Already have an account?",
    needAccount: "New to Northstar?",
    or: "or",
    returnHome: "Return to Northstar home",
    working: "Working…",
    voiceGuidanceLabel: "Voice guidance",
    voiceGuidanceHint: "Voice guidance is off until you enable it and select Speak.",
    signupSuccess: "Your request was accepted. If next steps are needed, they will be shown here.",
    loginSuccess: "You're signed in.",
    passkeyEnrollSuccess: "Your passkey was added.",
    recoverySuccess: "Your new passkey is ready. All previous sessions and passkeys were revoked. Save the new recovery codes now; they are shown only once. Recovery does not sign you in automatically; use the new passkey to sign in.",
    recoveryManagementTitle: "Manage recovery codes",
    recoveryManagementDescription: "Recovery codes are shown only when first issued or after successful account recovery. Save them securely; a new set invalidates previous codes.",
    recoveryCodesGenerate: "Generate new recovery codes",
    recoveryCodesNotice: "New codes are shown once. Save them securely; generating a new set invalidates the old codes.",
    recoveryGuideLabel: "Sentriq Recovery Assistant · guided mode",
    recoveryGuideDisclosure: "Rule-based guidance · no AI model is connected. Your question is handled in this page and is not sent or saved. Never enter passwords, recovery codes, or one-time codes in chat.",
    recoveryGuideInputLabel: "Ask about account recovery",
    recoveryGuideInputPlaceholder: "For example: I lost my phone",
    recoveryGuideSend: "Get guidance",
    recoveryGuideLostDevice: "First check whether another device can use a passkey synced with your account. If not, use the secure recovery form with one saved, unused recovery code. Never paste that code into chat.",
    recoveryGuideAnotherPasskey: "Try signing in from the other device with your passkey. If you cannot use it, open the secure recovery form and follow the displayed steps.",
    recoveryGuideHasCode: "Do not paste the code here. Open the secure recovery form and enter it only in the labeled recovery-code field.",
    recoveryGuideUnavailable: "Without a usable passkey or unused recovery code, this demo cannot securely restore access. There is no support or bypass path that can replace verification.",
    recoveryGuideAuthenticator: "A passkey is stored by your device or passkey provider. The device authorizes its use; Northstar verifies the signed response and does not receive your fingerprint or face data.",
    recoveryGuideSecretSafety: "This guide does not accept or save credentials. Do not share passwords, recovery codes, or one-time codes in chat. Use the secure recovery-code form instead.",
    recoveryGuideGeneral: "This guide can explain passkeys, another-device sign-in, and recovery codes. Never share a recovery code here; use the secure form on this page.",
    recoveryGuideResponseLabel: "Guidance",
    recoveryGuideDestinationLogin: "Open sign in",
    recoveryGuideDestinationRecovery: "Open secure recovery form",
  },
  ta: {
    emailLabel: "மின்னஞ்சல் முகவரி",
    displayNameLabel: "காட்சிப் பெயர்",
    invalidEmail: "சரியான மின்னஞ்சல் முகவரியை உள்ளிடவும்.",
    requiredName: "உங்கள் பெயரை உள்ளிடவும்.",
    correctFields: "குறிப்பிட்ட புலங்களைச் சரிபார்த்து மீண்டும் முயற்சிக்கவும்.",
    loginTitle: "உள்நுழை",
    loginIntro: "உங்கள் மின்னஞ்சலை உள்ளிட்டு, Passkey மூலம் தொடரவும். உங்கள் சாதனம் வழங்கினால், மின்னஞ்சல் இல்லாமலும் Passkey-ஐப் பயன்படுத்தலாம்.",
    signupTitle: "உங்கள் கணக்கை உருவாக்கவும்",
    signupIntro: "முதலில் உங்கள் மின்னஞ்சலை உள்ளிடவும். Passkey உருவாக்குவதற்கு முன் சரிபார்ப்புக் குறியீட்டை அனுப்புவோம்.",
    signUp: "தொடரவும்",
    emailContinue: "தொடரவும்",
    verifyEmailTitle: "உங்கள் மின்னஞ்சலைச் சரிபார்க்கவும்",
    verifyEmailIntro: "இந்த முகவரிக்கு அனுப்பப்பட்ட 12 எழுத்துக் குறியீட்டை உள்ளிடவும். குறியீடு 10 நிமிடங்களில் காலாவதியாகும்.",
    verificationCodeLabel: "மின்னஞ்சல் சரிபார்ப்புக் குறியீடு",
    verificationCodeHint: "இது மீட்பு குறியீடு அல்ல. மீட்பு குறியீட்டை உரையாடலில் பகிர வேண்டாம்.",
    verifyEmail: "மின்னஞ்சலைச் சரிபார்க்கவும்",
    resendVerification: "புதிய குறியீட்டை அனுப்பு",
    verificationResent: "இந்த முகவரியில் பதிவு செய்ய முடியுமானால், புதிய குறியீடு அனுப்பப்பட்டுள்ளது.",
    developmentInboxLabel: "மேம்பாட்டிற்காக மட்டும்: உள்ளூர் மின்னஞ்சல் குறியீட்டைக் காட்டு",
    developmentInboxHelp: "இந்த உள்ளூர் அஞ்சற்பெட்டி மேம்பாட்டிற்காக மட்டுமே. நேரடி பயன்பாட்டில் மின்னஞ்சல் அனுப்பும் சேவை தேவை.",
    developmentInboxLoaded: "உள்ளூர் சரிபார்ப்புக் குறியீடு ஏற்றப்பட்டது. அதை ரகசியமாக வைத்திருங்கள்.",
    invalidVerificationCode: "12 எழுத்துகள் கொண்ட மின்னஞ்சல் சரிபார்ப்புக் குறியீட்டை உள்ளிடவும்.",
    emailVerified: "மின்னஞ்சல் சரிபார்க்கப்பட்டது. இப்போது Passkey உருவாக்கவும்.",
    createPasskeyTitle: "உங்கள் Passkey-ஐ உருவாக்கவும்",
    createPasskeyDescription: "பாதுகாப்பாக உள்நுழைய உங்கள் கைபேசி அல்லது கணினியின் கைரேகை, முக அடையாளம் அல்லது PIN-ஐப் பயன்படுத்தவும். கடவுச்சொல் தேவையில்லை.",
    createPasskeyAction: "Passkey உருவாக்கவும்",
    saveRecoveryCodesTitle: "உங்கள் மீட்பு குறியீடுகளைச் சேமிக்கவும்",
    saveRecoveryCodesDescription: "Passkey-களை இழந்தால் கணக்கை மீட்க இந்த ஆறு குறியீடுகள் உதவும். ஒவ்வொரு குறியீடும் ஒருமுறை மட்டுமே பயன்படும். நம்பகமான கடவுச்சொல் மேலாளரில் அல்லது குறியாக்கப்பட்ட, பாதுகாப்பாக வைக்கப்பட்ட ஆஃப்லைன் நகலில் சேமிக்கவும்.",
    recoveryCodesCopy: "குறியீடுகளை நகலெடு",
    recoveryCodesCopied: "மீட்பு குறியீடுகள் நகலெடுக்கப்பட்டன. அவற்றைப் பாதுகாப்பான இடத்தில் வைக்கவும்.",
    recoveryCodesDownload: "குறியீடுகளை உரைக் கோப்பாகப் பதிவிறக்கு",
    recoveryCodesDownloadWarning: "பதிவிறக்கும் கோப்பில் கணக்கு மீட்புக்கான ரகசியங்கள் உள்ளன. அதை பாதுகாப்பாக வைத்து, கூடுதல் நகல்களை நீக்கவும்.",
    recoveryCodesPrint: "குறியீடுகளை அச்சிடு",
    recoveryCodesAcknowledgement: "இந்தக் குறியீடுகளைப் பாதுகாப்பாகச் சேமித்தேன். இவை ஒருமுறை மட்டுமே காட்டப்படும் என்பதைப் புரிந்துகொள்கிறேன்.",
    recoveryCodesContinue: "அமைப்பை முடிக்கவும்",
    clipboardUnavailable: "இங்கே நகலெடுப்பது கிடைக்கவில்லை. குறியீடுகளைத் தேர்ந்தெடுத்து கைமுறையாக நகலெடுக்கவும்.",
    setupComplete: "முடிந்தது",
    accountReadyTitle: "உங்கள் கணக்கு தயாராக உள்ளது",
    accountReadyDescription: "உங்கள் மின்னஞ்சல் சரிபார்க்கப்பட்டது, Passkey பதிவு செய்யப்பட்டது, ஆறு மீட்பு குறியீடுகள் வழங்கப்பட்டன.",
    verifiedEmailLabel: "சரிபார்க்கப்பட்ட மின்னஞ்சல்",
    registeredPasskeyLabel: "Passkey பதிவு செய்யப்பட்டது",
    recoveryCodesIssuedLabel: "மீட்பு குறியீடுகள் சேமிக்கப்பட்டன",
    continueToAccount: "உங்கள் கணக்கிற்குச் செல்லவும்",
    discoverableSignIn: "மின்னஞ்சல் இல்லாமல் Passkey பயன்படுத்தவும்",
    deviceLinkTitle: "புதிய சாதனத்தில் உள்நுழை",
    deviceLinkIntro: "மற்றொரு சாதனத்தில் நீங்கள் ஏற்கனவே உள்நுழைந்திருந்தால், அங்கிருந்து இந்தக் கோரிக்கையை ஒப்புதல் அளிக்கலாம். QR குறியீட்டை ஸ்கேன் செய்யத் தேவையில்லை.",
    deviceLinkStart: "எனது பழைய சாதனத்தில் ஒப்புதல் அளி",
    deviceLinkComparisonLabel: "கோரிக்கை ஒப்பீட்டுக் குறியீடு",
    deviceLinkComparisonHint: "உங்கள் பழைய சாதனத்தில் காட்டப்படும் குறியீடும் இதேதானா எனப் பார்த்த பிறகே ஒப்புதல் அளிக்கவும்.",
    deviceLinkPending: "உங்கள் பழைய சாதனத்தின் ஒப்புதலுக்காகக் காத்திருக்கிறது…",
    deviceLinkApproved: "உங்கள் கோரிக்கை ஒப்புதல் பெற்றது. முடிக்க இந்தச் சாதனத்தில் Passkey உருவாக்கவும்.",
    deviceLinkRejected: "கோரிக்கை நிராகரிக்கப்பட்டது. Passkey எதுவும் சேர்க்கப்படவில்லை.",
    deviceLinkExpired: "இந்தக் கோரிக்கை காலாவதியானது. மீண்டும் தொடங்கவும் அல்லது வேறு உள்நுழைவு முறையைத் தேர்ந்தெடுக்கவும்.",
    deviceLinkCreatePasskey: "இந்தச் சாதனத்தில் Passkey உருவாக்கவும்",
    deviceLinkCancel: "கோரிக்கையை ரத்து செய்",
    deviceLinkStartOver: "மற்றொரு கோரிக்கையை முயற்சி செய்",
    deviceApprovalTitle: "புதிய சாதனக் கோரிக்கைகள்",
    deviceApprovalDescription: "நீங்களே கோரிக்கையைத் தொடங்கியிருந்தும் ஒப்பீட்டுக் குறியீடு புதிய சாதனத்துடன் பொருந்தினாலும் மட்டுமே ஒப்புதல் அளிக்கவும்.",
    deviceApprovalEmpty: "நிலுவையில் உள்ள சாதனக் கோரிக்கைகள் இல்லை.",
    deviceApprovalPrompt: "நீங்கள் புதிய சாதனத்தைச் சேர்க்கிறீர்களா? Passkey மூலம் சரிபார்த்து இந்தக் கோரிக்கைக்கு ஒப்புதல் அளிக்கவும்.",
    deviceApprovalCodeLabel: "புதிய சாதனத்தில் காட்டிய குறியீட்டை உள்ளிடவும்",
    deviceApprovalCodeHint: "ஒப்புதல் அளிக்கும் முன் ஆறு எழுத்துகளையும் ஒப்பிடவும்.",
    deviceApprovalConfirmation: "இந்தக் குறியீடு புதிய சாதனத்தில் உள்ள குறியீட்டுடன் பொருந்துகிறது எனச் சரிபார்த்தேன்.",
    deviceApprovalApprove: "சரிபார்த்து ஒப்புதல் அளி",
    deviceApprovalReject: "கோரிக்கையை நிராகரி",
    deviceApprovalComplete: "புதிய சாதனத்திற்கு ஒப்புதல் அளிக்கப்பட்டது.",
    deviceApprovalRefresh: "கோரிக்கைகளைப் புதுப்பி",
    signIn: "உள்நுழை",
    passkeyLogin: "Passkey மூலம் உள்நுழை",
    passkeyEnroll: "Passkey சேர்க்கவும்",
    passkeyEnrollmentTitle: "Passkey சேர்க்கவும்",
    passkeyEnrollmentDescription: "இந்தச் சாதனத்தில் பாதுகாப்பாக உள்நுழைய Passkey சேர்க்கவும். உலாவி அறிவுறுத்தலைப் பின்பற்றவும்.",
    passkeyPrompt: "தொடர உங்கள் சாதனத்தில் உள்ள Passkey அறிவுறுத்தலைப் பின்பற்றவும்.",
    passkeyLoading: "Passkey சரிபார்ப்புக்காகக் காத்திருக்கிறது…",
    passkeyCancel: "Passkey உள்நுழைவை ரத்து செய்",
    recoveryCodeLabel: "மீட்பு குறியீடு",
    recoveryCodeHint: "சேமித்த மீட்பு குறியீடுகளில் ஒன்றை உள்ளிடவும். மீட்பு குறியீடுகள் மின்னஞ்சல் சரிபார்ப்புக் குறியீடுகளிலிருந்து வேறுபட்டவை.",
    recoveryLink: "மீட்பு குறியீட்டைப் பயன்படுத்து",
    recoveryTitle: "உங்கள் கணக்கை மீட்டெடுக்கவும்",
    recoveryIntro: "மின்னஞ்சல் முகவரியும் பயன்படுத்தப்படாத ஒரு மீட்பு குறியீடும் கொண்டு புதிய Passkey-ஐப் பதிவு செய்யவும். புதிய Passkey சரிபார்க்கப்படும் முன் மீட்பு உங்களை உள்நுழையச் செய்யாது.",
    beginRecovery: "மீட்பைத் தொடங்கு",
    completeRecovery: "மீட்பு குறியீட்டைச் சரிபார்",
    recoveryRegisterPasskey: "மாற்று Passkey-ஐப் பதிவு செய்",
    recoveryReplacementIntro: "உங்கள் மீட்பு குறியீடு ஏற்கப்பட்டது. மீட்பை முடிக்க புதிய Passkey-ஐப் பதிவு செய்யவும். பழைய அமர்வுகளும் Passkey-களும் ரத்து செய்யப்படும்.",
    recoveryCodesSave: "இந்த புதிய மீட்பு குறியீடுகளை இணையத்திற்கு வெளியே பாதுகாப்பாகச் சேமிக்கவும். இவை ஒருமுறை மட்டுமே காட்டப்படும். பயன்படுத்தப்படாத குறியீடு உள்ளவர் இந்தக் கணக்கை மீட்டெடுக்கலாம்.",
    recoveryPasskeyError: "மாற்று Passkey-ஐப் பதிவு செய்ய முடியவில்லை. மீண்டும் முயற்சிக்கவும் அல்லது ரத்து செய்து மற்றொரு பயன்படுத்தப்படாத குறியீட்டுடன் மீட்பைத் தொடங்கவும்.",
    recoveryCancelled: "மீட்பு ரத்து செய்யப்பட்டது. Passkey மாற்றப்படவில்லை.",
    backToSignIn: "உள்நுழைவுக்குத் திரும்பு",
    recoveryRequestAccepted: "மீட்டெடுக்கக்கூடிய கணக்குடன் விவரங்கள் பொருந்தினால், அடுத்த படிகள் இங்கே காட்டப்படும்.",
    genericFailure: "இந்தக் கோரிக்கையை முடிக்க முடியவில்லை. விவரங்களைச் சரிபார்த்து மீண்டும் முயற்சிக்கவும்.",
    rateLimited: "பல முயற்சிகள் செய்யப்பட்டுள்ளன. சிறிது நேரம் காத்திருந்து மீண்டும் முயற்சிக்கவும்.",
    networkError: "சேவையை அடைய முடியவில்லை. இணைப்பைச் சரிபார்த்து மீண்டும் முயற்சிக்கவும்.",
    sessionExpired: "உங்கள் அமர்வு காலாவதியானது. தொடர மீண்டும் உள்நுழையவும்.",
    passkeyFailure: "Passkey சரிபார்ப்பு நிறைவடையவில்லை. மீண்டும் முயற்சிக்கவும் அல்லது வேறு உள்நுழைவு முறையைத் தேர்ந்தெடுக்கவும்.",
    stepUpTitle: "இந்தச் செயலுக்கு சரிபார்ப்பு தேவை",
    stepUpIntro: "தொடர உங்கள் Passkey-ஐப் பயன்படுத்தவும். ரத்து செய்தால் எந்த மாற்றமும் செய்யப்படாது.",
    stepUpButton: "Passkey மூலம் தொடரவும்",
    stepUpWorking: "Passkey சரிபார்ப்புக்காகக் காத்திருக்கிறது…",
    stepUpCancel: "சரிபார்ப்பை ரத்துசெய்",
    exportTitle: "கணக்கு தரவை ஏற்றுமதி செய்",
    exportDescription: "உங்கள் கணக்குத் தரவின் ஏற்றுமதியைக் கோரவும். இந்தச் செயலுக்கு Passkey சரிபார்ப்பு தேவைப்படலாம்; இது உங்கள் அணுகல் கொள்கைக்கு உட்பட்டது.",
    policyDenied: "உங்கள் தற்போதைய அணுகல் கொள்கையின் கீழ் இந்தச் செயல் கிடைக்காது.",
    exportSuccess: "உங்கள் ஏற்றுமதி கோரிக்கை ஏற்கப்பட்டது. நிலையை இந்தப் பக்கத்தில் பார்க்கவும்.",
    deleteTitle: "கணக்கை நீக்கவும்",
    deleteDescription: "இந்தக் கணக்கும் அதன் சுயவிவரத் தரவும் நிரந்தரமாக நீக்கப்படும்; எல்லா அமர்வுகளும் முடிக்கப்படும்; சேமித்த அங்கீகாரிகளும் மீட்புக் குறியீடுகளும் அகற்றப்படும். நீக்குவதற்கு முன் Sentriq புதிய பாதுகாப்புச் சரிபார்ப்பைக் கோரும்.",
    deletePrompt: "தொடர்வதற்கு முன் அகற்றப்படும் தகவல்களைப் பாருங்கள்.",
    deleteConfirmLabel: "பாதுகாப்புச் சரிபார்ப்புக்குத் தொடரவும்",
    exportFormat: "பதிவிறக்க வடிவம்",
    jsonFormatHint: "கட்டமைக்கப்பட்ட JSON கோப்பு.",
    csvFormatHint: "விரிதாள் மென்பொருளில் திறக்கக்கூடிய அட்டவணை.",
    requestExport: "பாதுகாக்கப்பட்ட ஏற்றுமதியைக் கோரவும்",
    policyTitle: "பாதுகாக்கப்பட்ட செயல் கொள்கை",
    haveAccount: "ஏற்கனவே கணக்கு உள்ளதா?",
    needAccount: "Northstar-க்கு புதியவரா?",
    or: "அல்லது",
    returnHome: "Northstar முகப்புக்குத் திரும்பவும்",
    working: "செயல்படுகிறது…",
    voiceGuidanceLabel: "குரல் வழிகாட்டல்",
    voiceGuidanceHint: "குரல் வழிகாட்டல் இயல்பாக அணைக்கப்பட்டுள்ளது. அதை இயக்கி, பேசு என்பதைத் தேர்ந்தெடுக்கவும்.",
    signupSuccess: "உங்கள் கோரிக்கை ஏற்கப்பட்டது. அடுத்த படிகள் தேவைப்பட்டால், அவை இங்கே காட்டப்படும்.",
    loginSuccess: "நீங்கள் உள்நுழைந்துள்ளீர்கள்.",
    passkeyEnrollSuccess: "உங்கள் Passkey சேர்க்கப்பட்டது.",
    recoverySuccess: "உங்கள் புதிய Passkey தயாராக உள்ளது. முந்தைய எல்லா அமர்வுகளும் Passkey-களும் ரத்து செய்யப்பட்டன. புதிய மீட்பு குறியீடுகளை இப்போது சேமிக்கவும்; இவை ஒருமுறை மட்டுமே காட்டப்படும். மீட்புக்குப் பிறகு தானாக உள்நுழையப்படமாட்டீர்கள்; புதிய Passkey மூலம் உள்நுழையவும்.",
    recoveryManagementTitle: "மீட்பு குறியீடுகளை நிர்வகிக்கவும்",
    recoveryManagementDescription: "முதலில் வழங்கும் போதும் வெற்றிகரமான கணக்கு மீட்பிற்குப் பிறகும் மட்டுமே மீட்பு குறியீடுகள் காட்டப்படும். பாதுகாப்பாகச் சேமிக்கவும்; புதிய தொகுப்பு பழைய குறியீடுகளைச் செல்லாததாக்கும்.",
    recoveryCodesGenerate: "புதிய மீட்பு குறியீடுகளை உருவாக்கு",
    recoveryCodesNotice: "புதிய குறியீடுகள் ஒருமுறை மட்டுமே காட்டப்படும். பாதுகாப்பாகச் சேமிக்கவும்; புதிய தொகுப்பு பழைய குறியீடுகளைச் செல்லாததாக்கும்.",
    recoveryGuideLabel: "Sentriq மீட்பு உதவியாளர் · வழிகாட்டும் முறை",
    recoveryGuideDisclosure: "விதி அடிப்படையிலான வழிகாட்டல் · AI மாதிரி இணைக்கப்படவில்லை. உங்கள் கேள்வி இந்தப் பக்கத்தில் மட்டுமே கையாளப்படும்; அனுப்பப்படவோ சேமிக்கப்படவோ மாட்டாது. கடவுச்சொல், மீட்பு குறியீடு அல்லது ஒருமுறை குறியீட்டை உரையாடலில் உள்ளிட வேண்டாம்.",
    recoveryGuideInputLabel: "கணக்கு மீட்பு பற்றி கேளுங்கள்",
    recoveryGuideInputPlaceholder: "எடுத்துக்காட்டு: என் கைபேசி தொலைந்துவிட்டது",
    recoveryGuideSend: "வழிகாட்டலைப் பெறு",
    recoveryGuideLostDevice: "முதலில், உங்கள் கணக்குடன் ஒத்திசைக்கப்பட்ட Passkey-ஐ மற்றொரு சாதனம் பயன்படுத்த முடியுமா எனப் பாருங்கள். முடியாவிட்டால், சேமித்துப் பயன்படுத்தாத ஒரு மீட்பு குறியீட்டுடன் பாதுகாப்பான மீட்பு படிவத்தைப் பயன்படுத்தவும். அந்தக் குறியீட்டை உரையாடலில் ஒட்ட வேண்டாம்.",
    recoveryGuideAnotherPasskey: "மற்றொரு சாதனத்தில் உங்கள் Passkey-ஐப் பயன்படுத்தி உள்நுழைய முயற்சிக்கவும். அதைப் பயன்படுத்த முடியாவிட்டால், பாதுகாப்பான மீட்பு படிவத்தைத் திறந்து காட்டப்படும் படிகளைப் பின்பற்றவும்.",
    recoveryGuideHasCode: "குறியீட்டை இங்கே ஒட்ட வேண்டாம். பாதுகாப்பான மீட்பு படிவத்தைத் திறந்து, குறிக்கப்பட்ட மீட்பு குறியீட்டு புலத்தில் மட்டும் உள்ளிடவும்.",
    recoveryGuideUnavailable: "பயன்படுத்தக்கூடிய Passkey அல்லது பயன்படுத்தாத மீட்பு குறியீடு இல்லையெனில், இந்தச் செய்முறை அணுகலைப் பாதுகாப்பாக மீட்டுத் தர முடியாது. சரிபார்ப்பை மாற்றும் வழிமுறையோ பாதுகாப்புத் தாண்டும் வழியோ இல்லை.",
    recoveryGuideAuthenticator: "Passkey உங்கள் சாதனம் அல்லது Passkey வழங்குநரால் பாதுகாக்கப்படுகிறது. சாதனம் அதன் பயன்பாட்டை உறுதிப்படுத்தும்; கையொப்பமிட்ட பதிலை Northstar சரிபார்க்கும். உங்கள் கைரேகை அல்லது முகத் தரவை Northstar பெறாது.",
    recoveryGuideSecretSafety: "இந்த வழிகாட்டி சான்றுகளைப் பெறவோ சேமிக்கவோ செய்யாது. கடவுச்சொல், மீட்பு குறியீடு அல்லது ஒருமுறை குறியீட்டை உரையாடலில் பகிர வேண்டாம். பாதுகாப்பான மீட்பு குறியீட்டு படிவத்தைப் பயன்படுத்தவும்.",
    recoveryGuideGeneral: "Passkey, மற்றொரு சாதனத்தில் உள்நுழைதல், மீட்பு குறியீடுகள் ஆகியவற்றைப் பற்றி இந்த வழிகாட்டி விளக்க முடியும். மீட்பு குறியீட்டை இங்கே பகிர வேண்டாம்; இந்தப் பக்கத்தின் பாதுகாப்பான படிவத்தைப் பயன்படுத்தவும்.",
    recoveryGuideResponseLabel: "வழிகாட்டல்",
    recoveryGuideDestinationLogin: "உள்நுழைவைத் திறக்கவும்",
    recoveryGuideDestinationRecovery: "பாதுகாப்பான மீட்பு படிவத்தைத் திறக்கவும்",
  },
  hi: {
    emailLabel: "ईमेल पता",
    passwordLabel: "पासवर्ड",
    displayNameLabel: "दिखाया जाने वाला नाम",
    invalidEmail: "मान्य ईमेल पता दर्ज करें।",
    requiredName: "अपना नाम दर्ज करें।",
    correctFields: "चिह्नित फ़ील्ड जाँचकर फिर कोशिश करें।",
    loginTitle: "साइन इन करें",
    loginIntro: "अपने खाते के लिए निर्धारित पासवर्ड या Passkey का उपयोग करें।",
    signupTitle: "खाता बनाएँ",
    signupIntro: "खाता सेटअप का अनुरोध करने के लिए अपनी जानकारी दर्ज करें।",
    signUp: "खाता बनाएँ",
    signIn: "साइन इन करें",
    passkeyLogin: "Passkey से साइन इन करें",
    passkeyEnroll: "Passkey जोड़ें",
    passkeyEnrollmentTitle: "Passkey जोड़ें",
    passkeyEnrollmentDescription: "इस डिवाइस पर सुरक्षित रूप से साइन इन करने के लिए Passkey जोड़ें। ब्राउज़र के निर्देशों का पालन करें।",
    passkeyPrompt: "जारी रखने के लिए अपने डिवाइस पर Passkey संकेतों का पालन करें।",
    passkeyLoading: "Passkey सत्यापन की प्रतीक्षा हो रही है…",
    passkeyCancel: "Passkey साइन-इन रद्द करें",
    showPassword: "पासवर्ड दिखाएँ",
    hidePassword: "पासवर्ड छिपाएँ",
    recoveryCodeLabel: "रिकवरी कोड",
    recoveryCodeHint: "अपने सहेजे गए रिकवरी कोड में से एक दर्ज करें। रिकवरी कोड ईमेल सत्यापन कोड से अलग होते हैं।",
    recoveryLink: "रिकवरी कोड का उपयोग करें",
    recoveryTitle: "अपना खाता रिकवर करें",
    recoveryIntro: "अपने ईमेल से रिकवरी अनुरोध शुरू करें और स्क्रीन पर दिए चरणों का पालन करें। रिकवरी कोड ईमेल सत्यापन कोड से अलग होते हैं।",
    beginRecovery: "रिकवरी शुरू करें",
    completeRecovery: "रिकवरी पूरी करें",
    backToSignIn: "साइन इन पर वापस जाएँ",
    newPasswordLabel: "नया पासवर्ड",
    recoveryRequestAccepted: "यदि दी गई जानकारी वाले खाते की रिकवरी संभव है, तो अगले चरण यहाँ दिखेंगे।",
    passwordMinimum: "15–128 अक्षर इस्तेमाल करें। पासवर्ड को trim नहीं किया जाता।",
    genericFailure: "हम अनुरोध पूरा नहीं कर सके। विवरण जाँचकर फिर कोशिश करें।",
    rateLimited: "बहुत अधिक प्रयास हुए हैं। थोड़ी देर रुककर फिर कोशिश करें।",
    networkError: "सेवा से संपर्क नहीं हो सका। कनेक्शन जाँचकर फिर कोशिश करें।",
    sessionExpired: "आपका सत्र समाप्त हो गया। जारी रखने के लिए फिर साइन इन करें।",
    passkeyFailure: "Passkey सत्यापन पूरा नहीं हुआ। फिर कोशिश करें या दूसरा साइन-इन तरीका चुनें।",
    stepUpTitle: "इस कार्रवाई की पुष्टि करें",
    stepUpIntro: "जारी रखने के लिए अपनी Passkey का उपयोग करें। रद्द करने पर कोई बदलाव नहीं होगा।",
    stepUpButton: "Passkey से जारी रखें",
    stepUpWorking: "Passkey सत्यापन की प्रतीक्षा हो रही है…",
    stepUpCancel: "सत्यापन रद्द करें",
    exportTitle: "खाते का डेटा निर्यात करें",
    exportDescription: "अपने खाते के डेटा का निर्यात अनुरोध करें। इस कार्रवाई के लिए Passkey सत्यापन आवश्यक हो सकता है और यह आपकी मौजूदा पहुँच नीति के अधीन है।",
    policyDenied: "आपकी मौजूदा पहुँच नीति के तहत यह कार्रवाई उपलब्ध नहीं है।",
    exportSuccess: "आपका निर्यात अनुरोध स्वीकार किया गया। स्थिति के लिए यह पृष्ठ देखें।",
    deleteTitle: "खाता हटाएँ",
    deleteDescription: "यह खाता और इसकी प्रोफ़ाइल जानकारी स्थायी रूप से हटाई जाएगी, सभी सत्र बंद होंगे, और सहेजे गए प्रमाणक व रिकवरी कोड हटेंगे। हटाने से पहले Sentriq नई सुरक्षा जाँच माँगेगा।",
    deletePrompt: "आगे बढ़ने से पहले देखें कि क्या हटाया जाएगा।",
    deleteConfirmLabel: "सुरक्षा जाँच के लिए आगे बढ़ें",
    exportFormat: "डाउनलोड प्रारूप",
    jsonFormatHint: "एक संरचित JSON फ़ाइल।",
    csvFormatHint: "स्प्रेडशीट सॉफ़्टवेयर में खुलने वाली तालिका।",
    requestExport: "सुरक्षित निर्यात का अनुरोध करें",
    policyTitle: "सुरक्षित कार्रवाई नीति",
    haveAccount: "क्या आपका पहले से खाता है?",
    needAccount: "Northstar पर नए हैं?",
    or: "या",
    returnHome: "Northstar मुखपृष्ठ पर लौटें",
    working: "काम हो रहा है…",
    voiceGuidanceLabel: "आवाज़ में मार्गदर्शन",
    voiceGuidanceHint: "आवाज़ में मार्गदर्शन तब तक बंद है जब तक आप इसे चालू करके बोलें नहीं चुनते।",
    signupSuccess: "आपका अनुरोध स्वीकार किया गया। आगे के चरण आवश्यक हुए तो यहीं दिखेंगे।",
    loginSuccess: "आपने साइन इन कर लिया है।",
    passkeyEnrollSuccess: "आपकी Passkey जोड़ दी गई है।",
    recoverySuccess: "पुनर्प्राप्ति पूरी हो गई। अपने नए पासवर्ड से साइन इन करें, फिर Passkey जोड़ें। पुनर्प्राप्ति आपको अपने-आप साइन इन नहीं करती।",
    recoveryManagementTitle: "रिकवरी कोड प्रबंधित करें",
    recoveryManagementDescription: "पासवर्ड की पुष्टि करने के बाद कोड फिर से बनाएँ। नए कोड बनाने पर सभी पुराने कोड अमान्य हो जाते हैं।",
    recoveryCodesGenerate: "नए रिकवरी कोड बनाएँ",
    recoveryCodesNotice: "नए कोड केवल एक बार दिखाए जाते हैं। उन्हें सुरक्षित रखें; नया सेट पुराने कोड अमान्य करता है।",
  },
  te: {
    emailLabel: "ఇమెయిల్ చిరునామా",
    passwordLabel: "పాస్‌వర్డ్",
    displayNameLabel: "ప్రదర్శన పేరు",
    invalidEmail: "చెల్లుబాటు అయ్యే ఇమెయిల్ చిరునామాను నమోదు చేయండి.",
    requiredName: "మీ పేరును నమోదు చేయండి.",
    correctFields: "గుర్తించిన ఫీల్డ్‌లను తనిఖీ చేసి మళ్లీ ప్రయత్నించండి.",
    loginTitle: "సైన్ ఇన్ చేయండి",
    loginIntro: "మీ ఖాతాకు ఏర్పాటు చేసిన పాస్‌వర్డ్ లేదా Passkey ఉపయోగించండి.",
    signupTitle: "ఖాతా సృష్టించండి",
    signupIntro: "ఖాతా సెటప్ అభ్యర్థించడానికి మీ వివరాలు నమోదు చేయండి.",
    signUp: "ఖాతా సృష్టించండి",
    signIn: "సైన్ ఇన్ చేయండి",
    passkeyLogin: "Passkeyతో సైన్ ఇన్ చేయండి",
    passkeyEnroll: "Passkey జోడించండి",
    passkeyEnrollmentTitle: "Passkey జోడించండి",
    passkeyEnrollmentDescription: "ఈ పరికరంలో సురక్షితంగా సైన్ ఇన్ చేయడానికి Passkey జోడించండి. బ్రౌజర్ సూచనలను అనుసరించండి.",
    passkeyPrompt: "కొనసాగడానికి మీ పరికరంలోని Passkey సూచనలను అనుసరించండి.",
    passkeyLoading: "Passkey ధృవీకరణ కోసం వేచి ఉంది…",
    passkeyCancel: "Passkey సైన్-ఇన్ రద్దు చేయి",
    showPassword: "పాస్‌వర్డ్ చూపించు",
    hidePassword: "పాస్‌వర్డ్ దాచు",
    recoveryCodeLabel: "రికవరీ కోడ్",
    recoveryCodeHint: "మీరు భద్రపరచిన రికవరీ కోడ్‌లలో ఒకదాన్ని నమోదు చేయండి. రికవరీ కోడ్‌లు ఇమెయిల్ ధృవీకరణ కోడ్‌లకు వేరు.",
    recoveryLink: "రికవరీ కోడ్ ఉపయోగించండి",
    recoveryTitle: "మీ ఖాతాను తిరిగి పొందండి",
    recoveryIntro: "మీ ఇమెయిల్‌తో రికవరీ అభ్యర్థనను ప్రారంభించి, స్క్రీన్‌పై చూపిన దశలను అనుసరించండి. రికవరీ కోడ్‌లు ఇమెయిల్ ధృవీకరణ కోడ్‌లకు వేరు.",
    beginRecovery: "రికవరీ ప్రారంభించండి",
    completeRecovery: "రికవరీ పూర్తి చేయండి",
    backToSignIn: "సైన్ ఇన్‌కు తిరిగి వెళ్లండి",
    newPasswordLabel: "కొత్త పాస్‌వర్డ్",
    recoveryRequestAccepted: "వివరాలు తిరిగి పొందగల ఖాతాకు సరిపోతే, తదుపరి దశలు ఇక్కడ చూపబడతాయి.",
    passwordMinimum: "15–128 అక్షరాలు ఉపయోగించండి. పాస్‌వర్డ్‌ను trim చేయరు.",
    genericFailure: "ఆ అభ్యర్థనను పూర్తి చేయలేకపోయాం. వివరాలను తనిఖీ చేసి మళ్లీ ప్రయత్నించండి.",
    rateLimited: "చాలా ప్రయత్నాలు జరిగాయి. కొద్దిసేపు ఆగి మళ్లీ ప్రయత్నించండి.",
    networkError: "సేవను చేరుకోలేకపోయాం. కనెక్షన్ తనిఖీ చేసి మళ్లీ ప్రయత్నించండి.",
    sessionExpired: "మీ సెషన్ గడువు ముగిసింది. కొనసాగించడానికి మళ్లీ సైన్ ఇన్ చేయండి.",
    passkeyFailure: "Passkey ధృవీకరణ పూర్తికాలేదు. మళ్లీ ప్రయత్నించండి లేదా వేరే సైన్-ఇన్ పద్ధతిని ఎంచుకోండి.",
    stepUpTitle: "ఈ చర్యను ధృవీకరించండి",
    stepUpIntro: "కొనసాగడానికి మీ Passkey ఉపయోగించండి. మీరు రద్దు చేస్తే ఎలాంటి మార్పు జరగదు.",
    stepUpButton: "Passkeyతో కొనసాగండి",
    stepUpWorking: "Passkey ధృవీకరణ కోసం వేచి ఉంది…",
    stepUpCancel: "ధృవీకరణ రద్దు చేయి",
    exportTitle: "ఖాతా డేటాను ఎగుమతి చేయండి",
    exportDescription: "మీ ఖాతా డేటా ఎగుమతిని అభ్యర్థించండి. ఈ చర్యకు Passkey ధృవీకరణ అవసరం కావచ్చు మరియు మీ యాక్సెస్ పాలసీకి లోబడి ఉంటుంది.",
    policyDenied: "మీ ప్రస్తుత యాక్సెస్ పాలసీ ప్రకారం ఈ చర్య అందుబాటులో లేదు.",
    exportSuccess: "మీ ఎగుమతి అభ్యర్థన స్వీకరించబడింది. స్థితి కోసం ఈ పేజీని చూడండి.",
    deleteTitle: "ఖాతాను తొలగించండి",
    deleteDescription: "ఈ ఖాతా మరియు దాని ప్రొఫైల్ సమాచారం శాశ్వతంగా తొలగించబడతాయి, అన్ని సెషన్‌లు ముగుస్తాయి, సేవ్ చేసిన ప్రమాణీకరణ పరికరాలు మరియు రికవరీ కోడ్‌లు తొలగించబడతాయి. తొలగించే ముందు Sentriq కొత్త భద్రతా తనిఖీని కోరుతుంది.",
    deletePrompt: "కొనసాగించే ముందు ఏవి తొలగించబడతాయో సమీక్షించండి.",
    deleteConfirmLabel: "భద్రతా తనిఖీకి కొనసాగండి",
    exportFormat: "డౌన్‌లోడ్ ఫార్మాట్",
    jsonFormatHint: "నిర్మిత JSON ఫైల్.",
    csvFormatHint: "స్ప్రెడ్‌షీట్ సాఫ్ట్‌వేర్‌లో తెరవగల పట్టిక.",
    requestExport: "రక్షిత ఎగుమతిని అభ్యర్థించండి",
    policyTitle: "రక్షిత చర్య విధానం",
    haveAccount: "మీకు ఇప్పటికే ఖాతా ఉందా?",
    needAccount: "Northstar‌కు కొత్తవారా?",
    or: "లేదా",
    returnHome: "Northstar హోమ్‌కు తిరిగి వెళ్లండి",
    working: "పని జరుగుతోంది…",
    voiceGuidanceLabel: "వాయిస్ మార్గదర్శకం",
    voiceGuidanceHint: "మీరు దీన్ని ప్రారంభించి, మాట్లాడు ఎంచుకునే వరకు వాయిస్ మార్గదర్శకం ఆఫ్‌లో ఉంటుంది.",
    signupSuccess: "మీ అభ్యర్థన స్వీకరించబడింది. తదుపరి దశలు అవసరమైతే, అవి ఇక్కడ చూపబడతాయి.",
    loginSuccess: "మీరు సైన్ ఇన్ అయ్యారు.",
    passkeyEnrollSuccess: "మీ Passkey జోడించబడింది.",
    recoverySuccess: "రికవరీ పూర్తయింది. మీ కొత్త పాస్‌వర్డ్‌తో సైన్ ఇన్ చేసి, ఆపై Passkey జోడించండి. రికవరీతో మీరు స్వయంచాలకంగా సైన్ ఇన్ కారు.",
    recoveryManagementTitle: "రికవరీ కోడ్‌లను నిర్వహించండి",
    recoveryManagementDescription: "మీ పాస్‌వర్డ్‌ను నిర్ధారించిన తర్వాత కోడ్‌లను మళ్లీ రూపొందించండి. కొత్త కోడ్‌లు మునుపటి కోడ్‌లన్నింటినీ చెల్లనివిగా చేస్తాయి.",
    recoveryCodesGenerate: "కొత్త రికవరీ కోడ్‌లను రూపొందించండి",
    recoveryCodesNotice: "కొత్త కోడ్‌లు ఒక్కసారి మాత్రమే చూపబడతాయి. వాటిని భద్రంగా సేవ్ చేయండి; కొత్త సెట్ పాత కోడ్‌లను చెల్లనివిగా చేస్తుంది.",
  },
  ml: {
    emailLabel: "ഇമെയിൽ വിലാസം",
    passwordLabel: "പാസ്‌വേഡ്",
    displayNameLabel: "പ്രദർശന പേര്",
    invalidEmail: "സാധുവായ ഇമെയിൽ വിലാസം നൽകുക.",
    requiredName: "നിങ്ങളുടെ പേര് നൽകുക.",
    correctFields: "അടയാളപ്പെടുത്തിയ ഫീൽഡുകൾ പരിശോധിച്ച് വീണ്ടും ശ്രമിക്കുക.",
    loginTitle: "സൈൻ ഇൻ ചെയ്യുക",
    loginIntro: "നിങ്ങളുടെ അക്കൗണ്ടിനായി ക്രമീകരിച്ച പാസ്‌വേഡ് അല്ലെങ്കിൽ Passkey ഉപയോഗിക്കുക.",
    signupTitle: "അക്കൗണ്ട് സൃഷ്ടിക്കുക",
    signupIntro: "അക്കൗണ്ട് സജ്ജീകരണം അഭ്യർത്ഥിക്കാൻ നിങ്ങളുടെ വിവരങ്ങൾ നൽകുക.",
    signUp: "അക്കൗണ്ട് സൃഷ്ടിക്കുക",
    signIn: "സൈൻ ഇൻ ചെയ്യുക",
    passkeyLogin: "Passkey ഉപയോഗിച്ച് സൈൻ ഇൻ ചെയ്യുക",
    passkeyEnroll: "Passkey ചേർക്കുക",
    passkeyEnrollmentTitle: "Passkey ചേർക്കുക",
    passkeyEnrollmentDescription: "ഈ ഉപകരണത്തിൽ സുരക്ഷിതമായി സൈൻ ഇൻ ചെയ്യാൻ Passkey ചേർക്കുക. ബ്രൗസർ നിർദ്ദേശം പിന്തുടരുക.",
    passkeyPrompt: "തുടരാൻ നിങ്ങളുടെ ഉപകരണത്തിലെ Passkey നിർദ്ദേശം പാലിക്കുക.",
    passkeyLoading: "Passkey പരിശോധനയ്ക്കായി കാത്തിരിക്കുന്നു…",
    passkeyCancel: "Passkey സൈൻ-ഇൻ റദ്ദാക്കുക",
    showPassword: "പാസ്‌വേഡ് കാണിക്കുക",
    hidePassword: "പാസ്‌വേഡ് മറയ്ക്കുക",
    recoveryCodeLabel: "വീണ്ടെടുക്കൽ കോഡ്",
    recoveryCodeHint: "സൂക്ഷിച്ചിട്ടുള്ള വീണ്ടെടുക്കൽ കോഡുകളിൽ ഒന്ന് നൽകുക. വീണ്ടെടുക്കൽ കോഡുകൾ ഇമെയിൽ സ്ഥിരീകരണ കോഡുകളിൽ നിന്ന് വ്യത്യസ്തമാണ്.",
    recoveryLink: "വീണ്ടെടുക്കൽ കോഡ് ഉപയോഗിക്കുക",
    recoveryTitle: "നിങ്ങളുടെ അക്കൗണ്ട് വീണ്ടെടുക്കുക",
    recoveryIntro: "നിങ്ങളുടെ ഇമെയിൽ ഉപയോഗിച്ച് വീണ്ടെടുക്കൽ അഭ്യർത്ഥന ആരംഭിച്ച് സ്ക്രീനിലെ ഘട്ടങ്ങൾ പിന്തുടരുക. വീണ്ടെടുക്കൽ കോഡുകൾ ഇമെയിൽ സ്ഥിരീകരണ കോഡുകളിൽ നിന്ന് വ്യത്യസ്തമാണ്.",
    beginRecovery: "വീണ്ടെടുക്കൽ ആരംഭിക്കുക",
    completeRecovery: "വീണ്ടെടുക്കൽ പൂർത്തിയാക്കുക",
    backToSignIn: "സൈൻ ഇൻ ചെയ്യുന്നതിലേക്ക് മടങ്ങുക",
    newPasswordLabel: "പുതിയ പാസ്‌വേഡ്",
    recoveryRequestAccepted: "വീണ്ടെടുക്കാനാകുന്ന അക്കൗണ്ടുമായി വിവരങ്ങൾ പൊരുത്തപ്പെട്ടാൽ അടുത്ത ഘട്ടങ്ങൾ ഇവിടെ കാണിക്കും.",
    passwordMinimum: "15–128 അക്ഷരങ്ങൾ ഉപയോഗിക്കുക. പാസ്‌വേഡ് trim ചെയ്യില്ല.",
    genericFailure: "ആ അഭ്യർത്ഥന പൂർത്തിയാക്കാനായില്ല. വിവരങ്ങൾ പരിശോധിച്ച് വീണ്ടും ശ്രമിക്കുക.",
    rateLimited: "വളരെയധികം ശ്രമങ്ങളുണ്ട്. കുറച്ച് സമയം കാത്തിരുന്ന് വീണ്ടും ശ്രമിക്കുക.",
    networkError: "സേവനവുമായി ബന്ധപ്പെടാനായില്ല. കണക്ഷൻ പരിശോധിച്ച് വീണ്ടും ശ്രമിക്കുക.",
    sessionExpired: "നിങ്ങളുടെ സെഷൻ കാലഹരണപ്പെട്ടു. തുടരാൻ വീണ്ടും സൈൻ ഇൻ ചെയ്യുക.",
    passkeyFailure: "Passkey പരിശോധന പൂർത്തിയായില്ല. വീണ്ടും ശ്രമിക്കുകയോ മറ്റൊരു സൈൻ-ഇൻ രീതി തിരഞ്ഞെടുക്കുകയോ ചെയ്യുക.",
    stepUpTitle: "ഈ നടപടി സ്ഥിരീകരിക്കുക",
    stepUpIntro: "തുടരാൻ നിങ്ങളുടെ Passkey ഉപയോഗിക്കുക. റദ്ദാക്കിയാൽ മാറ്റമൊന്നും വരുത്തില്ല.",
    stepUpButton: "Passkey ഉപയോഗിച്ച് തുടരുക",
    stepUpWorking: "Passkey പരിശോധനയ്ക്കായി കാത്തിരിക്കുന്നു…",
    stepUpCancel: "പരിശോധന റദ്ദാക്കുക",
    exportTitle: "അക്കൗണ്ട് ഡാറ്റ എക്സ്പോർട്ട് ചെയ്യുക",
    exportDescription: "നിങ്ങളുടെ അക്കൗണ്ട് ഡാറ്റയുടെ എക്സ്പോർട്ട് അഭ്യർത്ഥിക്കുക. ഈ നടപടിക്ക് Passkey പരിശോധന ആവശ്യമായേക്കാം; ഇത് നിങ്ങളുടെ ആക്സസ് നയത്തിന് വിധേയമാണ്.",
    policyDenied: "നിങ്ങളുടെ നിലവിലെ ആക്സസ് നയപ്രകാരം ഈ നടപടി ലഭ്യമല്ല.",
    exportSuccess: "നിങ്ങളുടെ എക്സ്പോർട്ട് അഭ്യർത്ഥന സ്വീകരിച്ചു. നില ഈ പേജിൽ പരിശോധിക്കുക.",
    deleteTitle: "അക്കൗണ്ട് ഇല്ലാതാക്കുക",
    deleteDescription: "ഈ അക്കൗണ്ടും അതിന്റെ പ്രൊഫൈൽ വിവരങ്ങളും സ്ഥിരമായി ഇല്ലാതാക്കും; എല്ലാ സെഷനുകളും അവസാനിപ്പിക്കും; സൂക്ഷിച്ച പ്രാമാണീകരണികളും വീണ്ടെടുക്കൽ കോഡുകളും നീക്കും. ഇല്ലാതാക്കുന്നതിന് മുമ്പ് Sentriq പുതിയ സുരക്ഷാ പരിശോധന ആവശ്യപ്പെടും.",
    deletePrompt: "തുടരുന്നതിന് മുമ്പ് നീക്കം ചെയ്യപ്പെടുന്നവ പരിശോധിക്കുക.",
    deleteConfirmLabel: "സുരക്ഷാ പരിശോധനയിലേക്ക് തുടരുക",
    exportFormat: "ഡൗൺലോഡ് ഫോർമാറ്റ്",
    jsonFormatHint: "ക്രമീകരിച്ച JSON ഫയൽ.",
    csvFormatHint: "സ്പ്രെഡ്ഷീറ്റ് സോഫ്റ്റ്‌വെയറിൽ തുറക്കാവുന്ന പട്ടിക.",
    requestExport: "സംരക്ഷിത എക്സ്പോർട്ട് അഭ്യർത്ഥിക്കുക",
    policyTitle: "സംരക്ഷിത പ്രവർത്തന നയം",
    haveAccount: "നിങ്ങൾക്ക് ഇതിനകം അക്കൗണ്ടുണ്ടോ?",
    needAccount: "Northstar-ൽ പുതിയ ആളാണോ?",
    or: "അല്ലെങ്കിൽ",
    returnHome: "Northstar ഹോമിലേക്ക് മടങ്ങുക",
    working: "പ്രവർത്തിക്കുന്നു…",
    voiceGuidanceLabel: "ശബ്ദ മാർഗ്ഗനിർദ്ദേശം",
    voiceGuidanceHint: "നിങ്ങൾ ഇത് പ്രവർത്തനക്ഷമമാക്കി Speak തിരഞ്ഞെടുക്കുന്നതുവരെ ശബ്ദ മാർഗ്ഗനിർദ്ദേശം ഓഫായിരിക്കും.",
    signupSuccess: "നിങ്ങളുടെ അഭ്യർത്ഥന സ്വീകരിച്ചു. തുടർനടപടികൾ ആവശ്യമെങ്കിൽ ഇവിടെ കാണിക്കും.",
    loginSuccess: "നിങ്ങൾ സൈൻ ഇൻ ചെയ്തു.",
    passkeyEnrollSuccess: "നിങ്ങളുടെ Passkey ചേർത്തു.",
    recoverySuccess: "വീണ്ടെടുക്കൽ പൂർത്തിയായി. നിങ്ങളുടെ പുതിയ പാസ്‌വേഡ് ഉപയോഗിച്ച് സൈൻ ഇൻ ചെയ്ത് Passkey ചേർക്കുക. വീണ്ടെടുക്കൽ നിങ്ങളെ സ്വയം സൈൻ ഇൻ ചെയ്യിക്കില്ല.",
    recoveryManagementTitle: "വീണ്ടെടുക്കൽ കോഡുകൾ കൈകാര്യം ചെയ്യുക",
    recoveryManagementDescription: "നിങ്ങളുടെ പാസ്‌വേഡ് സ്ഥിരീകരിച്ച ശേഷം കോഡുകൾ വീണ്ടും സൃഷ്ടിക്കുക. പുതിയ കോഡുകൾ പഴയ എല്ലാ കോഡുകളും അസാധുവാക്കും.",
    recoveryCodesGenerate: "പുതിയ വീണ്ടെടുക്കൽ കോഡുകൾ സൃഷ്ടിക്കുക",
    recoveryCodesNotice: "പുതിയ കോഡുകൾ ഒരിക്കൽ മാത്രമേ കാണിക്കൂ. സുരക്ഷിതമായി സൂക്ഷിക്കുക; പുതിയ സെറ്റ് പഴയ കോഡുകൾ അസാധുവാക്കും.",
  },
  kn: {
    emailLabel: "ಇಮೇಲ್ ವಿಳಾಸ",
    passwordLabel: "ಪಾಸ್‌ವರ್ಡ್",
    displayNameLabel: "ಪ್ರದರ್ಶನ ಹೆಸರು",
    invalidEmail: "ಮಾನ್ಯ ಇಮೇಲ್ ವಿಳಾಸವನ್ನು ನಮೂದಿಸಿ.",
    requiredName: "ನಿಮ್ಮ ಹೆಸರನ್ನು ನಮೂದಿಸಿ.",
    correctFields: "ಗುರುತಿಸಿದ ಕ್ಷೇತ್ರಗಳನ್ನು ಪರಿಶೀಲಿಸಿ ಮತ್ತೆ ಪ್ರಯತ್ನಿಸಿ.",
    loginTitle: "ಸೈನ್ ಇನ್ ಮಾಡಿ",
    loginIntro: "ನಿಮ್ಮ ಖಾತೆಗೆ ಹೊಂದಿಸಿರುವ ಪಾಸ್‌ವರ್ಡ್ ಅಥವಾ Passkey ಬಳಸಿ.",
    signupTitle: "ಖಾತೆ ರಚಿಸಿ",
    signupIntro: "ಖಾತೆ ಸೆಟಪ್ ಕೋರಲು ನಿಮ್ಮ ವಿವರಗಳನ್ನು ನಮೂದಿಸಿ.",
    signUp: "ಖಾತೆ ರಚಿಸಿ",
    signIn: "ಸೈನ್ ಇನ್ ಮಾಡಿ",
    passkeyLogin: "Passkey ಬಳಸಿ ಸೈನ್ ಇನ್ ಮಾಡಿ",
    passkeyEnroll: "Passkey ಸೇರಿಸಿ",
    passkeyEnrollmentTitle: "Passkey ಸೇರಿಸಿ",
    passkeyEnrollmentDescription: "ಈ ಸಾಧನದಲ್ಲಿ ಸುರಕ್ಷಿತವಾಗಿ ಸೈನ್ ಇನ್ ಮಾಡಲು Passkey ಸೇರಿಸಿ. ಬ್ರೌಸರ್ ಸೂಚನೆಗಳನ್ನು ಅನುಸರಿಸಿ.",
    passkeyPrompt: "ಮುಂದುವರಿಯಲು ನಿಮ್ಮ ಸಾಧನದಲ್ಲಿನ Passkey ಸೂಚನೆ ಅನುಸರಿಸಿ.",
    passkeyLoading: "Passkey ಪರಿಶೀಲನೆಗಾಗಿ ಕಾಯಲಾಗುತ್ತಿದೆ…",
    passkeyCancel: "Passkey ಸೈನ್-ಇನ್ ರದ್ದುಮಾಡಿ",
    showPassword: "ಪಾಸ್‌ವರ್ಡ್ ತೋರಿಸಿ",
    hidePassword: "ಪಾಸ್‌ವರ್ಡ್ ಮರೆಮಾಡಿ",
    recoveryCodeLabel: "ಮರುಪಡೆಯುವಿಕೆ ಕೋಡ್",
    recoveryCodeHint: "ನೀವು ಉಳಿಸಿರುವ ಮರುಪಡೆಯುವಿಕೆ ಕೋಡ್‌ಗಳಲ್ಲಿ ಒಂದನ್ನು ನಮೂದಿಸಿ. ಮರುಪಡೆಯುವಿಕೆ ಕೋಡ್‌ಗಳು ಇಮೇಲ್ ಪರಿಶೀಲನೆ ಕೋಡ್‌ಗಳಿಂದ ಭಿನ್ನವಾಗಿವೆ.",
    recoveryLink: "ಮರುಪಡೆಯುವಿಕೆ ಕೋಡ್ ಬಳಸಿ",
    recoveryTitle: "ನಿಮ್ಮ ಖಾತೆಯನ್ನು ಮರುಪಡೆಯಿರಿ",
    recoveryIntro: "ನಿಮ್ಮ ಇಮೇಲ್ ಬಳಸಿ ಮರುಪಡೆಯುವಿಕೆ ವಿನಂತಿಯನ್ನು ಪ್ರಾರಂಭಿಸಿ ಮತ್ತು ಪರದೆಯಲ್ಲಿರುವ ಹಂತಗಳನ್ನು ಅನುಸರಿಸಿ. ಮರುಪಡೆಯುವಿಕೆ ಕೋಡ್‌ಗಳು ಇಮೇಲ್ ಪರಿಶೀಲನೆ ಕೋಡ್‌ಗಳಿಂದ ಭಿನ್ನವಾಗಿವೆ.",
    beginRecovery: "ಮರುಪಡೆಯುವಿಕೆ ಪ್ರಾರಂಭಿಸಿ",
    completeRecovery: "ಮರುಪಡೆಯುವಿಕೆ ಪೂರ್ಣಗೊಳಿಸಿ",
    backToSignIn: "ಸೈನ್ ಇನ್‌ಗೆ ಹಿಂತಿರುಗಿ",
    newPasswordLabel: "ಹೊಸ ಪಾಸ್‌ವರ್ಡ್",
    recoveryRequestAccepted: "ವಿವರಗಳು ಮರುಪಡೆಯಬಹುದಾದ ಖಾತೆಗೆ ಹೊಂದಿದರೆ, ಮುಂದಿನ ಹಂತಗಳನ್ನು ಇಲ್ಲಿ ತೋರಿಸಲಾಗುತ್ತದೆ.",
    passwordMinimum: "15–128 ಅಕ್ಷರಗಳನ್ನು ಬಳಸಿ. ಪಾಸ್‌ವರ್ಡ್‌ಗಳನ್ನು trim ಮಾಡುವುದಿಲ್ಲ.",
    genericFailure: "ಆ ವಿನಂತಿಯನ್ನು ಪೂರ್ಣಗೊಳಿಸಲಾಗಲಿಲ್ಲ. ವಿವರಗಳನ್ನು ಪರಿಶೀಲಿಸಿ ಮತ್ತೆ ಪ್ರಯತ್ನಿಸಿ.",
    rateLimited: "ಹಲವಾರು ಪ್ರಯತ್ನಗಳಾಗಿವೆ. ಸ್ವಲ್ಪ ಸಮಯ ಕಾಯ್ದು ಮತ್ತೆ ಪ್ರಯತ್ನಿಸಿ.",
    networkError: "ಸೇವೆಯನ್ನು ಸಂಪರ್ಕಿಸಲಾಗಲಿಲ್ಲ. ಸಂಪರ್ಕವನ್ನು ಪರಿಶೀಲಿಸಿ ಮತ್ತೆ ಪ್ರಯತ್ನಿಸಿ.",
    sessionExpired: "ನಿಮ್ಮ ಸೆಷನ್ ಅವಧಿ ಮುಗಿದಿದೆ. ಮುಂದುವರಿಯಲು ಮತ್ತೆ ಸೈನ್ ಇನ್ ಮಾಡಿ.",
    passkeyFailure: "Passkey ಪರಿಶೀಲನೆ ಪೂರ್ಣಗೊಳ್ಳಲಿಲ್ಲ. ಮತ್ತೆ ಪ್ರಯತ್ನಿಸಿ ಅಥವಾ ಬೇರೆ ಸೈನ್-ಇನ್ ವಿಧಾನ ಆಯ್ಕೆಮಾಡಿ.",
    stepUpTitle: "ಈ ಕ್ರಿಯೆಯನ್ನು ಪರಿಶೀಲಿಸಿ",
    stepUpIntro: "ಮುಂದುವರಿಯಲು ನಿಮ್ಮ Passkey ಬಳಸಿ. ನೀವು ರದ್ದುಗೊಳಿಸಿದರೆ ಯಾವುದೇ ಬದಲಾವಣೆ ಆಗುವುದಿಲ್ಲ.",
    stepUpButton: "Passkey ಬಳಸಿ ಮುಂದುವರಿಯಿರಿ",
    stepUpWorking: "Passkey ಪರಿಶೀಲನೆಗಾಗಿ ಕಾಯಲಾಗುತ್ತಿದೆ…",
    stepUpCancel: "ಪರಿಶೀಲನೆ ರದ್ದುಗೊಳಿಸಿ",
    exportTitle: "ಖಾತೆ ಡೇಟಾವನ್ನು ರಫ್ತು ಮಾಡಿ",
    exportDescription: "ನಿಮ್ಮ ಖಾತೆ ಡೇಟಾದ ರಫ್ತಿಗೆ ವಿನಂತಿಸಿ. ಈ ಕ್ರಿಯೆಗೆ Passkey ಪರಿಶೀಲನೆ ಅಗತ್ಯವಾಗಬಹುದು ಮತ್ತು ನಿಮ್ಮ ಪ್ರವೇಶ ನೀತಿಗೆ ಒಳಪಟ್ಟಿರುತ್ತದೆ.",
    policyDenied: "ನಿಮ್ಮ ಪ್ರಸ್ತುತ ಪ್ರವೇಶ ನೀತಿಯಡಿ ಈ ಕ್ರಿಯೆ ಲಭ್ಯವಿಲ್ಲ.",
    exportSuccess: "ನಿಮ್ಮ ರಫ್ತು ವಿನಂತಿಯನ್ನು ಸ್ವೀಕರಿಸಲಾಗಿದೆ. ಸ್ಥಿತಿಗಾಗಿ ಈ ಪುಟವನ್ನು ನೋಡಿ.",
    deleteTitle: "ಖಾತೆಯನ್ನು ಅಳಿಸಿ",
    deleteDescription: "ಈ ಖಾತೆ ಮತ್ತು ಅದರ ಪ್ರೊಫೈಲ್ ಮಾಹಿತಿಯನ್ನು ಶಾಶ್ವತವಾಗಿ ಅಳಿಸಲಾಗುತ್ತದೆ, ಎಲ್ಲಾ ಸೆಷನ್‌ಗಳಿಂದ ಸೈನ್ ಔಟ್ ಮಾಡಲಾಗುತ್ತದೆ, ಉಳಿಸಿದ ದೃಢೀಕರಣ ಸಾಧನಗಳು ಮತ್ತು ಮರುಪಡೆಯುವಿಕೆ ಕೋಡ್‌ಗಳನ್ನು ತೆಗೆದುಹಾಕಲಾಗುತ್ತದೆ. ಅಳಿಸುವ ಮೊದಲು Sentriq ಹೊಸ ಭದ್ರತಾ ಪರಿಶೀಲನೆಯನ್ನು ಕೇಳುತ್ತದೆ.",
    deletePrompt: "ಮುಂದುವರಿಯುವ ಮೊದಲು ಯಾವುದು ತೆಗೆದುಹಾಕಲಾಗುತ್ತದೆ ಎಂಬುದನ್ನು ಪರಿಶೀಲಿಸಿ.",
    deleteConfirmLabel: "ಭದ್ರತಾ ಪರಿಶೀಲನೆಗೆ ಮುಂದುವರಿಯಿರಿ",
    exportFormat: "ಡೌನ್‌ಲೋಡ್ ಸ್ವರೂಪ",
    jsonFormatHint: "ರಚನೆಯ JSON ಫೈಲ್.",
    csvFormatHint: "ಸ್ಪ್ರೆಡ್‌ಶೀಟ್ ತಂತ್ರಾಂಶದಲ್ಲಿ ತೆರೆಯಬಹುದಾದ ಕೋಷ್ಟಕ.",
    requestExport: "ರಕ್ಷಿತ ರಫ್ತಿಗೆ ವಿನಂತಿಸಿ",
    policyTitle: "ರಕ್ಷಿತ ಕಾರ್ಯ ನೀತಿ",
    haveAccount: "ನಿಮಗೆ ಈಗಾಗಲೇ ಖಾತೆಯಿದೆಯೇ?",
    needAccount: "Northstar‌ಗೆ ಹೊಸಬರೇ?",
    or: "ಅಥವಾ",
    returnHome: "Northstar ಮುಖಪುಟಕ್ಕೆ ಮರಳಿ",
    working: "ಕಾರ್ಯನಿರ್ವಹಿಸುತ್ತಿದೆ…",
    voiceGuidanceLabel: "ಧ್ವನಿ ಮಾರ್ಗದರ್ಶನ",
    voiceGuidanceHint: "ನೀವು ಅದನ್ನು ಸಕ್ರಿಯಗೊಳಿಸಿ Speak ಆಯ್ಕೆಮಾಡುವವರೆಗೆ ಧ್ವನಿ ಮಾರ್ಗದರ್ಶನ ಆಫ್ ಆಗಿರುತ್ತದೆ.",
    signupSuccess: "ನಿಮ್ಮ ವಿನಂತಿಯನ್ನು ಸ್ವೀಕರಿಸಲಾಗಿದೆ. ಮುಂದಿನ ಹಂತಗಳು ಅಗತ್ಯವಿದ್ದರೆ ಇಲ್ಲಿ ತೋರಿಸಲಾಗುತ್ತದೆ.",
    loginSuccess: "ನೀವು ಸೈನ್ ಇನ್ ಆಗಿದ್ದೀರಿ.",
    passkeyEnrollSuccess: "ನಿಮ್ಮ Passkey ಸೇರಿಸಲಾಗಿದೆ.",
    recoverySuccess: "ಮರುಪಡೆಯುವಿಕೆ ಪೂರ್ಣಗೊಂಡಿದೆ. ನಿಮ್ಮ ಹೊಸ ಪಾಸ್‌ವರ್ಡ್‌ನಿಂದ ಸೈನ್ ಇನ್ ಮಾಡಿ, ನಂತರ Passkey ಸೇರಿಸಿ. ಮರುಪಡೆಯುವಿಕೆ ನಿಮ್ಮನ್ನು ಸ್ವಯಂಚಾಲಿತವಾಗಿ ಸೈನ್ ಇನ್ ಮಾಡುವುದಿಲ್ಲ.",
    recoveryManagementTitle: "ಮರುಪಡೆಯುವಿಕೆ ಕೋಡ್‌ಗಳನ್ನು ನಿರ್ವಹಿಸಿ",
    recoveryManagementDescription: "ನಿಮ್ಮ ಪಾಸ್‌ವರ್ಡ್ ದೃಢಪಡಿಸಿದ ನಂತರ ಕೋಡ್‌ಗಳನ್ನು ಮರುರಚಿಸಿ. ಹೊಸ ಕೋಡ್‌ಗಳು ಹಿಂದಿನ ಎಲ್ಲಾ ಕೋಡ್‌ಗಳನ್ನು ಅಮಾನ್ಯಗೊಳಿಸುತ್ತವೆ.",
    recoveryCodesGenerate: "ಹೊಸ ಮರುಪಡೆಯುವಿಕೆ ಕೋಡ್‌ಗಳನ್ನು ರಚಿಸಿ",
    recoveryCodesNotice: "ಹೊಸ ಕೋಡ್‌ಗಳನ್ನು ಒಮ್ಮೆ ಮಾತ್ರ ತೋರಿಸಲಾಗುತ್ತದೆ. ಸುರಕ್ಷಿತವಾಗಿ ಉಳಿಸಿ; ಹೊಸ ಸೆಟ್ ಹಳೆಯ ಕೋಡ್‌ಗಳನ್ನು ಅಮಾನ್ಯಗೊಳಿಸುತ್ತದೆ.",
  },
} satisfies Record<string, Record<string, string>>;

export const accessPreferenceTranslations = {
  en: { voiceEnabled: "Enable spoken guidance", voiceEnabledHint: "Speech stays off until you enable it and press Speak.", voiceDisabledStatus: "Spoken guidance is off.", privacyDescription: "Only language, selected voice and enable toggle, speech rate, contrast, text size, motion, and keyboard guide are stored. Passwords, credentials, form values, and API data are not stored." },
  ta: { voiceEnabled: "குரல் வழிகாட்டலை இயக்கு", voiceEnabledHint: "இயக்கி பேசு என்பதைத் தேர்ந்தெடுக்கும் வரை பேச்சு அணைந்திருக்கும்.", voiceDisabledStatus: "குரல் வழிகாட்டல் அணைக்கப்பட்டுள்ளது.", privacyDescription: "மொழி, தேர்ந்தெடுத்த குரல் மற்றும் இயக்கத் தேர்வு, பேச்சு வேகம், மாறுபாடு, எழுத்தளவு, இயக்கம், விசைப்பலகை வழிகாட்டி மட்டும் சேமிக்கப்படும். கடவுச்சொல், சான்று, படிவ மதிப்பு அல்லது API தரவு சேமிக்கப்படாது." },
  hi: { voiceEnabled: "बोला गया मार्गदर्शन चालू करें", voiceEnabledHint: "इसे चालू करके बोलें दबाने तक आवाज़ बंद रहेगी।", voiceDisabledStatus: "बोला गया मार्गदर्शन बंद है।", privacyDescription: "केवल भाषा, चुनी गई आवाज़ और उसका चालू/बंद विकल्प, बोलने की गति, कंट्रास्ट, पाठ आकार, गति और कीबोर्ड मार्गदर्शिका सहेजी जाती है। पासवर्ड, क्रेडेंशियल, फ़ॉर्म मान और API डेटा सहेजे नहीं जाते।" },
  te: { voiceEnabled: "వాయిస్ మార్గదర్శకాన్ని ప్రారంభించండి", voiceEnabledHint: "మీరు ప్రారంభించి మాట్లాడు నొక్కే వరకు మాటలు ఆఫ్‌లో ఉంటాయి.", voiceDisabledStatus: "వాయిస్ మార్గదర్శకం ఆఫ్‌లో ఉంది.", privacyDescription: "భాష, ఎంచుకున్న వాయిస్ మరియు దాని ప్రారంభ ఎంపిక, మాటల వేగం, కాంట్రాస్ట్, టెక్స్ట్ పరిమాణం, చలనం, కీబోర్డ్ మార్గదర్శకం మాత్రమే సేవ్ అవుతాయి. పాస్‌వర్డ్‌లు, ఆధారాలు, ఫారమ్ విలువలు లేదా API డేటా నిల్వ చేయబడవు." },
  ml: { voiceEnabled: "ശബ്ദ മാർഗ്ഗനിർദ്ദേശം പ്രവർത്തനക്ഷമമാക്കുക", voiceEnabledHint: "പ്രവർത്തനക്ഷമമാക്കി Speak അമർത്തുന്നതുവരെ ശബ്ദം ഓഫായിരിക്കും.", voiceDisabledStatus: "ശബ്ദ മാർഗ്ഗനിർദ്ദേശം ഓഫാണ്.", privacyDescription: "ഭാഷ, തിരഞ്ഞെടുത്ത ശബ്ദവും അതിന്റെ പ്രവർത്തന നിലയും, സംസാര വേഗം, കോൺട്രാസ്റ്റ്, ടെക്സ്റ്റ് വലുപ്പം, ചലനം, കീബോർഡ് മാർഗ്ഗനിർദ്ദേശം എന്നിവ മാത്രം സൂക്ഷിക്കുന്നു. പാസ്‌വേഡുകൾ, ക്രെഡൻഷ്യലുകൾ, ഫോം മൂല്യങ്ങൾ, API ഡാറ്റ എന്നിവ സൂക്ഷിക്കില്ല." },
  kn: { voiceEnabled: "ಧ್ವನಿ ಮಾರ್ಗದರ್ಶನ ಸಕ್ರಿಯಗೊಳಿಸಿ", voiceEnabledHint: "ಸಕ್ರಿಯಗೊಳಿಸಿ Speak ಒತ್ತುವವರೆಗೆ ಮಾತು ಆಫ್ ಆಗಿರುತ್ತದೆ.", voiceDisabledStatus: "ಧ್ವನಿ ಮಾರ್ಗದರ್ಶನ ಆಫ್ ಆಗಿದೆ.", privacyDescription: "ಭಾಷೆ, ಆಯ್ದ ಧ್ವನಿ ಮತ್ತು ಅದರ ಸಕ್ರಿಯ ಸ್ಥಿತಿ, ಮಾತಿನ ವೇಗ, ಕಾಂಟ್ರಾಸ್ಟ್, ಪಠ್ಯದ ಗಾತ್ರ, ಚಲನೆ ಮತ್ತು ಕೀಬೋರ್ಡ್ ಮಾರ್ಗದರ್ಶಿ ಮಾತ್ರ ಉಳಿಯುತ್ತವೆ. ಪಾಸ್‌ವರ್ಡ್‌ಗಳು, ರುಜುವಾತುಗಳು, ಫಾರ್ಮ್ ಮೌಲ್ಯಗಳು ಅಥವಾ API ಡೇಟಾ ಉಳಿಯುವುದಿಲ್ಲ." },
} satisfies Record<string, Record<string, string>>;

/** Static, allowlisted speech for real authentication screens; never interpolate form or server values. */
export const liveAuthVoiceGuides = {
  en: {
    liveAuth: "Enter your email and continue with a passkey, or choose passkey sign-in without email if your device supports it. Use a recovery code only in the secure recovery form.",
    authError: "The sign-in request could not be completed. Review the message on this screen and try again. Keep passwords and recovery codes private.",
    otpTotp: "One-time passcodes, or OTPs, and authenticator-app codes, or TOTP, are sensitive. Enter them only on the sign-in screen you opened. Never share a code in chat or support messages. Recovery codes are separate backup credentials.",
  },
  ta: {
    liveAuth: "உங்கள் மின்னஞ்சலை உள்ளிட்டு Passkey மூலம் தொடரவும்; உங்கள் சாதனம் ஆதரித்தால் மின்னஞ்சல் இல்லாத Passkey உள்நுழைவையும் தேர்ந்தெடுக்கலாம். மீட்பு குறியீட்டை பாதுகாப்பான மீட்பு படிவத்தில் மட்டும் உள்ளிடவும்.",
    authError: "உள்நுழைவு கோரிக்கையை முடிக்க முடியவில்லை. இந்தத் திரையில் உள்ள செய்தியைப் பார்த்து மீண்டும் முயற்சிக்கவும். கடவுச்சொற்களையும் மீட்பு குறியீடுகளையும் பகிர வேண்டாம்.",
    otpTotp: "ஒருமுறை கடவுக்குறியீடுகள் (OTP) மற்றும் அங்கீகரிப்பு செயலி குறியீடுகள் (TOTP) உணர்வுபூர்வமானவை. நீங்கள் திறந்த உள்நுழைவுத் திரையில் மட்டுமே அவற்றை உள்ளிடவும். உரையாடல் அல்லது ஆதரவு செய்தியில் குறியீட்டைப் பகிர வேண்டாம். மீட்பு குறியீடுகள் தனியான காப்பு சான்றுகள்.",
  },
  hi: {
    liveAuth: "अपने खाते के लिए निर्धारित साइन-इन तरीका चुनें। आप पासवर्ड या Passkey चुन सकते हैं। सहेजे गए रिकवरी कोड का उपयोग केवल रिकवरी स्क्रीन पर करें।",
    authError: "साइन-इन अनुरोध पूरा नहीं हो सका। इस स्क्रीन पर दिया संदेश पढ़कर फिर कोशिश करें। पासवर्ड और रिकवरी कोड निजी रखें।",
    otpTotp: "एक बार इस्तेमाल होने वाले पासकोड (OTP) और ऑथेंटिकेटर ऐप के कोड (TOTP) संवेदनशील हैं। उन्हें केवल उसी साइन-इन स्क्रीन पर दर्ज करें जिसे आपने खोला है। चैट या सहायता संदेश में कोई कोड साझा न करें। रिकवरी कोड अलग बैकअप क्रेडेंशियल हैं।",
  },
  te: {
    liveAuth: "మీ ఖాతాకు ఏర్పాటు చేసిన సైన్-ఇన్ పద్ధతిని ఉపయోగించండి. పాస్‌వర్డ్ లేదా Passkey ఎంచుకోవచ్చు. భద్రపరిచిన రికవరీ కోడ్‌ను రికవరీ స్క్రీన్‌లో మాత్రమే ఉపయోగించండి.",
    authError: "సైన్-ఇన్ అభ్యర్థనను పూర్తి చేయలేకపోయాం. ఈ స్క్రీన్‌లోని సందేశాన్ని చదివి మళ్లీ ప్రయత్నించండి. పాస్‌వర్డ్‌లు, రికవరీ కోడ్‌లను రహస్యంగా ఉంచండి.",
    otpTotp: "ఒకసారి ఉపయోగించే పాస్‌కోడ్‌లు (OTP), ఆథెంటికేటర్ యాప్ కోడ్‌లు (TOTP) సున్నితమైనవి. మీరు తెరిచిన సైన్-ఇన్ స్క్రీన్‌లో మాత్రమే వాటిని నమోదు చేయండి. చాట్ లేదా సహాయ సందేశంలో కోడ్‌ను పంచుకోవద్దు. రికవరీ కోడ్‌లు వేరు బ్యాకప్ ఆధారాలు.",
  },
  ml: {
    liveAuth: "നിങ്ങളുടെ അക്കൗണ്ടിനായി ക്രമീകരിച്ച സൈൻ-ഇൻ രീതി ഉപയോഗിക്കുക. പാസ്‌വേഡ് അല്ലെങ്കിൽ Passkey തിരഞ്ഞെടുക്കാം. സൂക്ഷിച്ച വീണ്ടെടുക്കൽ കോഡ് വീണ്ടെടുക്കൽ സ്ക്രീനിൽ മാത്രം ഉപയോഗിക്കുക.",
    authError: "സൈൻ-ഇൻ അഭ്യർത്ഥന പൂർത്തിയാക്കാനായില്ല. ഈ സ്ക്രീനിലെ സന്ദേശം പരിശോധിച്ച് വീണ്ടും ശ്രമിക്കുക. പാസ്‌വേഡുകളും വീണ്ടെടുക്കൽ കോഡുകളും രഹസ്യമായി സൂക്ഷിക്കുക.",
    otpTotp: "ഒറ്റത്തവണ പാസ്‌കോഡുകളും (OTP) ഓതന്റിക്കേറ്റർ ആപ്പ് കോഡുകളും (TOTP) രഹസ്യമായി സൂക്ഷിക്കണം. നിങ്ങൾ തുറന്ന സൈൻ-ഇൻ സ്ക്രീനിൽ മാത്രം അവ നൽകുക. ചാറ്റിലോ സഹായ സന്ദേശത്തിലോ കോഡ് പങ്കിടരുത്. വീണ്ടെടുക്കൽ കോഡുകൾ വേറിട്ട ബാക്കപ്പ് ക്രെഡൻഷ്യലുകളാണ്.",
  },
  kn: {
    liveAuth: "ನಿಮ್ಮ ಖಾತೆಗೆ ಹೊಂದಿಸಿರುವ ಸೈನ್-ಇನ್ ವಿಧಾನವನ್ನು ಬಳಸಿ. ಪಾಸ್‌ವರ್ಡ್ ಅಥವಾ Passkey ಆಯ್ಕೆಮಾಡಬಹುದು. ಉಳಿಸಿದ ಮರುಪಡೆಯುವಿಕೆ ಕೋಡ್ ಅನ್ನು ಮರುಪಡೆಯುವಿಕೆ ಪರದೆಯಲ್ಲೇ ಬಳಸಿ.",
    authError: "ಸೈನ್-ಇನ್ ವಿನಂತಿಯನ್ನು ಪೂರ್ಣಗೊಳಿಸಲಾಗಲಿಲ್ಲ. ಈ ಪರದೆಯ ಸಂದೇಶವನ್ನು ನೋಡಿ ಮತ್ತೆ ಪ್ರಯತ್ನಿಸಿ. ಪಾಸ್‌ವರ್ಡ್ ಮತ್ತು ಮರುಪಡೆಯುವಿಕೆ ಕೋಡ್‌ಗಳನ್ನು ಖಾಸಗಿಯಾಗಿ ಇಡಿ.",
    otpTotp: "ಒಮ್ಮೆ ಬಳಸುವ ಪಾಸ್‌ಕೋಡ್‌ಗಳು (OTP) ಮತ್ತು ಆಥೆಂಟಿಕೇಟರ್ ಆಪ್ ಕೋಡ್‌ಗಳು (TOTP) ಸೂಕ್ಷ್ಮವಾಗಿವೆ. ನೀವು ತೆರೆದ ಸೈನ್-ಇನ್ ಪರದೆಯಲ್ಲೇ ಅವುಗಳನ್ನು ನಮೂದಿಸಿ. ಚಾಟ್ ಅಥವಾ ಬೆಂಬಲ ಸಂದೇಶದಲ್ಲಿ ಕೋಡ್ ಹಂಚಿಕೊಳ್ಳಬೇಡಿ. ಮರುಪಡೆಯುವಿಕೆ ಕೋಡ್‌ಗಳು ಪ್ರತ್ಯೇಕ ಬ್ಯಾಕಪ್ ರುಜುವಾತುಗಳು.",
  },
} satisfies Record<string, Record<string, string>>;
